### ISSUE TITLE
Example config leads to a traffic spike on APRS-IS

### ISSUE THREAD

**Issue by hessu** [BrandMeister/bm-rpt2aprs#14]
Hi,

I'm Hessu, OH7LZB. I run the aprs.fi site and maintain the aprsc APRS-IS server software.

I've been looking at a rather noticeable traffic spike which happens every 30 minutes, pretty close on :00:00 and :30:00. For example: https://twitter.com/aprsfi/status/1161629579108388864

One of the sources seems to be this Brandmeister script, I believe. When looking closely at the packets at the peak time, I see a 1-second peak spike of 400 packets per second, where 277 per second have a tocall of APBM1S. This is currently not a critical problem, but if it grows, it may eventually be a kind of a little DOS attack. The normal APRS-IS packet rate is closer to 75 packets/second. The installation instructions in README.md nicely tell people to run it at :00:00 and :30:00 and thanks to NTP this leads to a synchronised packet flood.

Could you please make this script sleep a longish random time, 0-10 minutes for example, before starting to send packets? And somehow make an effort to get people to upgrade it to get the peak go away? Even better, make it distribute the packet sending evenly across the whole 30 minutes interval?

Something like usleep(random_int(0, 10 * 60 * 1000000)); should do. Microsecond-accurate sleep will distribute the packets more evenly, better than sleep().

Thanks!

**Comment by stefansaraev** [comment]
hi @hessu 

I think the peak you are seeing is not caused by this script, but by slightly modified and well.. "optimized" version, maintained by me and in use on 4 - 5 master servers. I've added some delays now, moved it out of cron and asked people in charge of those masters to update. However, I advise those who use the upstream version (this script as-is) to not use cron.

I apologize for any inconvenience this may have caused.

**Comment by nonoo** [comment]
@stefansaraev can you please send a pull request with the randomized delays so I can merge it?

**Comment by stefansaraev** [comment]
@nonoo yours is slow enough, so it doesn't need delays ;)
